// <auto-generated />
using System;
using JoeSync.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JoeSync.Core.Data.Migrations
{
    [DbContext(typeof(JoeSyncDbContext))]
    partial class JoeSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JoeSync.Core.Data.Entities.DimAusgabe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ausgabe")
                        .HasColumnType("int");

                    b.Property<int?>("AusgabeIDU")
                        .HasColumnType("int");

                    b.Property<string>("Ausgabenkuerzel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Jahr")
                        .HasColumnType("int");

                    b.Property<string>("Schuljahr")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Ausgabenkuerzel")
                        .IsUnique();

                    b.ToTable("dim_ausgaben", "curated");
                });

            modelBuilder.Entity("JoeSync.Core.Data.Entities.DimDate", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayID")
                        .HasColumnType("int");

                    b.Property<int>("DayNum")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MonthID")
                        .HasColumnType("int");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MonthNum")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.ToTable("dim_date", "curated");
                });

            modelBuilder.Entity("JoeSync.Core.Data.Entities.MatomoActionDetailEnriched", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Browser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Edition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdSite")
                        .HasColumnType("int");

                    b.Property<long>("IdVisit")
                        .HasColumnType("bigint");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SearchPatternIdu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SearchPatternTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Seitenart")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ServerDate")
                        .HasColumnType("date");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubRubrik")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TimeSpent")
                        .HasColumnType("int");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlClean")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlLastPathElement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlParameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlPathElementOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlPathElementTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlPathFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisitDuration")
                        .HasColumnType("int");

                    b.Property<string>("VisitorId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdSite", "IdVisit");

                    b.HasIndex("IdSite", "Timestamp");

                    b.ToTable("matomo_action_details_enriched", "curated");
                });

            modelBuilder.Entity("JoeSync.Core.Data.Entities.MatomoDailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgVisitDuration")
                        .HasColumnType("int");

                    b.Property<int>("BounceCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Downloads")
                        .HasColumnType("int");

                    b.Property<int>("Events")
                        .HasColumnType("int");

                    b.Property<int>("IdSite")
                        .HasColumnType("int");

                    b.Property<int>("PageViews")
                        .HasColumnType("int");

                    b.Property<int>("Searches")
                        .HasColumnType("int");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UniqueDownloads")
                        .HasColumnType("int");

                    b.Property<int>("UniquePageViews")
                        .HasColumnType("int");

                    b.Property<int>("UniqueVisitors")
                        .HasColumnType("int");

                    b.Property<int>("Visits")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSite", "Date")
                        .IsUnique();

                    b.ToTable("matomo_daily_summary", "curated");
                });

            modelBuilder.Entity("JoeSync.Core.Data.Entities.MatomoMediaAudioDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgCompletion")
                        .HasColumnType("float");

                    b.Property<int>("AvgTimeWatched")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Edition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("FinishRate")
                        .HasColumnType("float");

                    b.Property<int>("Finishes")
                        .HasColumnType("int");

                    b.Property<int>("IdSite")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<double>("PlayRate")
                        .HasColumnType("float");

                    b.Property<int>("Plays")
                        .HasColumnType("int");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UniqueVisitorsPlays")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UrlLastPathElement")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdSite", "Date", "Label");

                    b.ToTable("matomo_media_audio_daily", "curated");
                });

            modelBuilder.Entity("JoeSync.Core.Data.Entities.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RowsAffected")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "StartTime");

                    b.ToTable("SyncLog", "logging");
                });
#pragma warning restore 612, 618
        }
    }
}
